import os
import json
import logging
import hashlib
import time
from datetime import datetime
from typing import List, Dict, Any, Optional
from openai import OpenAI
from pydantic import ValidationError
from services.database import DatabaseClient
from services.vector_contract import CanonicalVector

class VectorStore:
    """
    Manages embedding generation, token budgeting, and vector interactions with Azure SQL.
    Strictly enforces Canonical Vector Contracts and specific retrieval modes.
    """
    def __init__(self):
        self.openai_client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))
        self.model = "text-embedding-3-small" # The 1536-dimensional model
        self.db = DatabaseClient()
        
    def get_embedding(self, text: str) -> List[float]:
        try:
            # Efficiency constraint check: In a full app, check token budgets here.
            text = text.replace("\n", " ")
            response = self.openai_client.embeddings.create(input=[text], model=self.model)
            return response.data[0].embedding
        except Exception as e:
            logging.error(f"OpenAI Embedding Error (Token budget exceeded or connection failed): {e}")
            raise e

    def add_document(self, filename: str, content: str, metadata: dict) -> bool:
        """
        Legacy compatibility wrapper for adding a document to the vector store.
        Maps simple inputs to the Modernized Canonical Vector Contract.
        """
        # Generate a stable vector_id from filename and timestamp
        timestamp = metadata.get('timestamp_epoch', time.time())
        vector_id = f"VEC-{hashlib.md5(filename.encode()).hexdigest()[:8]}-{int(timestamp)}"
        
        # Hash the raw content
        raw_hash = hashlib.sha256(content.encode()).hexdigest()
        
        # Determine Source Type based on classification
        classification = metadata.get('classification', 'Unknown')
        source_type = 'Trip' if 'Uber' in classification or 'Private' in classification else 'Artifact'
        
        # Map metadata to canonical fields
        vector_data = {
            "vector_id": vector_id,
            "source_type": source_type,
            "timestamp_utc": datetime.fromtimestamp(timestamp),
            "raw_text_hash": raw_hash,
            "source_pointer": metadata.get('artifact_id', metadata.get('source_url', filename)),
            "derivation_reason": f"Modernized Ingestion [{classification}] from {filename}",
            # embedding will be generated by add_vector if not provided
        }
        
        return self.add_vector(vector_data)

    def add_vector(self, vector_data: dict) -> bool:
        """
        Validates and adds a canonical vector to the System_Vectors table.
        Prevents non-compliant data accumulation.
        """
        try:
            # Generate embedding if not provided
            if "embedding" not in vector_data:
                vector_data["embedding"] = self.get_embedding(vector_data.get("derivation_reason", ""))
                
            # 1. Enforce Canonical Vector Contract
            canonical = CanonicalVector(**vector_data)
        except ValidationError as e:
            logging.error(f"Vector Validation Failed. Missing or malformed data: {e}")
            return False

        # 2. Database Merge/Insert
        conn = self.db.get_connection()
        if not conn: return False
        cursor = conn.cursor()
        
        # SQL must include all NOT NULL columns for legacy DB maintenance
        sql = """
        MERGE INTO System_Vectors AS target
        USING (SELECT ? AS vector_id) AS source
        ON (target.vector_id = source.vector_id)
        WHEN MATCHED THEN
            UPDATE SET 
                source_type=?, timestamp_utc=?, vehicle_id=?, driver_id=?, 
                confidence_score=?, embedding_model_version=?, raw_text_hash=?, 
                source_pointer=?, derivation_reason=?, embedding=CAST(CAST(? AS NVARCHAR(MAX)) AS VECTOR(1536))
        WHEN NOT MATCHED THEN
            INSERT (vector_id, source_type, timestamp_utc, vehicle_id, driver_id, confidence_score, 
                    embedding_model_version, raw_text_hash, source_pointer, derivation_reason, embedding)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CAST(CAST(? AS NVARCHAR(MAX)) AS VECTOR(1536)));
        """
        
        emb_json = json.dumps(canonical.embedding)
        
        # PRIVACY GHOSTS: Safe placeholders for DB NOT NULL constraints
        safe_vin_hash = "sha256-summitos-privacy-standard"
        safe_driver_hash = "sha256-system-autonomous-segment"
        
        # DB Compatibility Mapping for source_type (CHECK constraint alignment)
        db_source_type_map = {
            "Artifact": "Operations",
            "Trip": "Passenger",
            "Charge": "Operations",
            "Ops": "Operations"
        }
        db_source_type = db_source_type_map.get(canonical.source_type, "Operations")
        
        params = (
            canonical.vector_id,
            db_source_type, canonical.timestamp_utc, safe_vin_hash, safe_driver_hash,
            1.0, self.model, canonical.raw_text_hash,
            canonical.source_pointer, canonical.derivation_reason, emb_json,
            # For NOT MATCHED
            canonical.vector_id, db_source_type, canonical.timestamp_utc, safe_vin_hash, safe_driver_hash,
            1.0, self.model, canonical.raw_text_hash,
            canonical.source_pointer, canonical.derivation_reason, emb_json
        )
        
        try:
            cursor.execute(sql, params)
            conn.commit()
            logging.info(f"Modernized Canonical Vector {canonical.vector_id} securely persisted.")
            return True
        except Exception as e:
            logging.error(f"System_Vectors SQL Insert Error for vector {canonical.vector_id}: {e}")
            return False
        finally:
            conn.close()

    def query_evidence_mode(self, query_text: str, n_results=5, confidence_threshold=0.40) -> List[Dict[str, Any]]:
        """
        Retrieve verifiable records under 'Evidence Mode'.
        This mode strictly returns semantic matches above standard confidence without applying LLM inference smoothing.
        Returns the raw pointers to the source data based on vector similarity.
        """
        emb = self.get_embedding(query_text)
        emb_json = json.dumps(emb)
        
        # We calculate confidence as (1.0 - Distance). Distance 0 means identical.
        # So we filter where (1.0 - Distance) >= confidence_threshold, which means Distance <= (1.0 - confidence_threshold)
        max_dist = 1.0 - confidence_threshold
        
        sql = """
            SELECT TOP (?)
                vector_id, source_type, timestamp_utc, vehicle_id, driver_id, confidence_score as original_confidence,
                raw_text_hash, source_pointer, derivation_reason,
                1.0 - VECTOR_DISTANCE('cosine', embedding, CAST(CAST(? AS NVARCHAR(MAX)) AS VECTOR(1536))) as search_confidence
            FROM System_Vectors
            WHERE VECTOR_DISTANCE('cosine', embedding, CAST(CAST(? AS NVARCHAR(MAX)) AS VECTOR(1536))) <= ?
            ORDER BY search_confidence DESC
        """
        
        results = self.db.execute_query_params(sql, (n_results, emb_json, emb_json, max_dist))
        
        if results:
            logging.info(f"Evidence Mode Retrieved {len(results)} exact matches exceeding {confidence_threshold} confidence.")
        else:
            logging.warning("Evidence Mode returned no matches. Inference/Hypothesis not supported for this query.")
            
        return results

    def query_insight_mode(self, query_text: str, n_results=10) -> str:
        """
        Insight Mode: Pattern detection and correlation. Uses LLM to synthesize raw evidence.
        """
        evidence = self.query_evidence_mode(query_text, n_results=n_results, confidence_threshold=0.5)
        if not evidence:
            return "No verifiable patterns detected in the system for this query."
            
        context = "\\n".join([f"Evidence {i+1}: Pointer={e['source_pointer']}, Confidence={e['original_confidence']}, Reason={e['derivation_reason']}" for i, e in enumerate(evidence)])
        
        prompt = f"Detect patterns and correlations from the following systemic evidence based on the query: '{query_text}'.\\n\\nEvidence:\\n{context}"
        try:
            response = self.openai_client.chat.completions.create(
                model="gpt-4o",
                messages=[{"role": "system", "content": "You are the Agentic SQL Vector System Insight Mode. Identify patterns. Do not invent facts."},
                          {"role": "user", "content": prompt}]
            )
            return response.choices[0].message.content
        except Exception as e:
            logging.error(f"Insight generation failed: {e}")
            return f"Insight generation failed: {e}"

    def query_narrative_mode(self, query_text: str, n_results=5) -> str:
        """
        Narrative Mode: Investor-facing synthesis with explicit citations to source pointers.
        """
        evidence = self.query_evidence_mode(query_text, n_results=n_results, confidence_threshold=0.6)
        if not evidence:
            return "Hypothesis rejected: Claims cannot be supported by verifiable data."
            
        context = "\\n".join([f"Source {e['source_pointer']} (Hash: {e['raw_text_hash']}): {e['derivation_reason']}" for e in evidence])
        
        prompt = f"Synthesize an investor-facing report answering: '{query_text}'.\\nYou MUST explicitly cite the Source pointers (e.g., [Source R-12345]) for every claim made.\\n\\nValidated Data:\\n{context}"
        try:
            response = self.openai_client.chat.completions.create(
                model="gpt-4o",
                messages=[{"role": "system", "content": "You are the COS Tesla Investor Reporting System. Truth overrides convenience. Cite all claims explicitly using provided Source pointers."},
                          {"role": "user", "content": prompt}]
            )
            return response.choices[0].message.content
        except Exception as e:
            logging.error(f"Narrative generation failed: {e}")
            return f"Narrative generation failed: {e}"
